### ISSUE TITLE
Is it tagged correctly?

### ISSUE THREAD

**Issue by HLFH** [searxng/fasttext-predict#3]
Hi @dalf,

When I [go there](https://github.com/searxng/fasttext-predict/commit/0807442015e0b5a72211120cb090e382af21a850):
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

When I clone the repo, and use the `git describe` command:
```
git describe           

fatal : Aucune étiquette ne peut décrire '5077baca8962bf071d366876c025684ca58b0fe2'.
Essayez --always, ou créez des étiquettes.
```

`python-fasttext-predict-git` cannot be packaged on Arch Linux.
The PKGBUILD [pkgver() function](https://wiki.archlinux.org/title/VCS_package_guidelines#The_pkgver()_function) does not work with how this repo is currently tagged.

**Comment by dalf** [comment]
The issue should be fixed now: I forgot to `git push --force` to take into account a minor change of the description in `setup.py`.

**Comment by HLFH** [comment]
Thanks! Problem solved.

`python-fasttext-predict-git` is now [released as well on the AUR](https://aur.archlinux.org/packages/python-fasttext-predict-git).
